const express=require("express"),path=require("path"),{Pool}=require("pg"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken");
const app=express(),PORT=process.env.PORT||3000,DB=process.env.DATABASE_URL,SECRET=process.env.JWT_SECRET||"troque-esta-chave";
if(!DB){console.error("DATABASE_URL não configurada");process.exit(1)}
const pool=new Pool({connectionString:DB,ssl:{rejectUnauthorized:false}});
app.use(express.json({limit:"10mb"})); app.use(express.static(__dirname));
async function init(){await pool.query(`
CREATE TABLE IF NOT EXISTS app_users(id BIGSERIAL PRIMARY KEY,nome TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'consulta',ativo BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS producers(id TEXT PRIMARY KEY,codigo TEXT,nome TEXT NOT NULL,localidade TEXT,tanqueiro_nome TEXT,caminhao TEXT,whatsapp TEXT,whatsapp_tanqueiro TEXT,updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS milk_entries(id TEXT PRIMARY KEY,produtor_id TEXT REFERENCES producers(id) ON DELETE CASCADE,data DATE NOT NULL,hora TEXT,litros NUMERIC(14,3) DEFAULT 0,localidade TEXT,tanqueiro_nome TEXT,caminhao TEXT,rota TEXT,origem_relatorio TEXT,updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS debts(id TEXT PRIMARY KEY,produtor_id TEXT REFERENCES producers(id) ON DELETE CASCADE,data DATE NOT NULL,descricao TEXT NOT NULL,valor NUMERIC(14,2) DEFAULT 0,updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS debt_payments(id TEXT PRIMARY KEY,debito_id TEXT REFERENCES debts(id) ON DELETE CASCADE,produtor_id TEXT REFERENCES producers(id) ON DELETE CASCADE,data DATE NOT NULL,valor NUMERIC(14,2) DEFAULT 0,updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS fortnight_payments(id TEXT PRIMARY KEY,produtor_id TEXT REFERENCES producers(id) ON DELETE CASCADE,mes TEXT,quinzena TEXT,data_pagamento DATE,litros NUMERIC(14,3) DEFAULT 0,valor_pago NUMERIC(14,2) DEFAULT 0,updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS fortnight_closures(id TEXT PRIMARY KEY,mes TEXT,quinzena TEXT,data_inicio DATE,data_fim DATE,fechado BOOLEAN DEFAULT TRUE,fechado_em TIMESTAMPTZ,resumo JSONB DEFAULT '{}'::jsonb,updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS audit_logs(id BIGSERIAL PRIMARY KEY,created_at TIMESTAMPTZ DEFAULT NOW(),user_id BIGINT,usuario TEXT,action TEXT NOT NULL,table_name TEXT NOT NULL,record_id TEXT,details JSONB);
`)}
const token=u=>jwt.sign({id:u.id,email:u.email,role:u.role,nome:u.nome},SECRET,{expiresIn:"12h"});
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||"").replace("Bearer ",""),SECRET);next()}catch(e){res.status(401).json({error:"Não autenticado"})}}
app.get("/api/health",async(req,res)=>{try{let q=await pool.query("SELECT NOW() agora");res.json({ok:true,database:true,agora:q.rows[0].agora})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post("/api/setup-admin",async(req,res)=>{try{let n=(await pool.query("SELECT COUNT(*)::int n FROM app_users")).rows[0].n;if(n)return res.status(409).json({error:"Administrador inicial já criado"});let{nome,email,senha}=req.body;if(!nome||!email||!senha||senha.length<6)return res.status(400).json({error:"Dados inválidos"});let h=await bcrypt.hash(senha,12),q=await pool.query("INSERT INTO app_users(nome,email,password_hash,role) VALUES($1,$2,$3,'administrador') RETURNING id,nome,email,role,ativo",[nome,email.toLowerCase(),h]);res.json({user:q.rows[0],token:token(q.rows[0])})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/login",async(req,res)=>{try{let{email,senha}=req.body,q=await pool.query("SELECT * FROM app_users WHERE email=$1",[String(email).toLowerCase()]),u=q.rows[0];if(!u||!u.ativo||!await bcrypt.compare(String(senha),u.password_hash))return res.status(401).json({error:"Usuário ou senha inválidos"});res.json({user:{id:u.id,nome:u.nome,email:u.email,role:u.role},token:token(u)})}catch(e){res.status(500).json({error:e.message})}});
const cfg={producers:["id","codigo","nome","localidade","tanqueiro_nome","caminhao","whatsapp","whatsapp_tanqueiro"],milk_entries:["id","produtor_id","data","hora","litros","localidade","tanqueiro_nome","caminhao","rota","origem_relatorio"],debts:["id","produtor_id","data","descricao","valor"],debt_payments:["id","debito_id","produtor_id","data","valor"],fortnight_payments:["id","produtor_id","mes","quinzena","data_pagamento","litros","valor_pago"],fortnight_closures:["id","mes","quinzena","data_inicio","data_fim","fechado","fechado_em","resumo"]};
app.get("/api/data/:t",auth,async(req,res)=>{let c=cfg[req.params.t];if(!c)return res.status(404).json({error:"Tabela inválida"});try{res.json((await pool.query(`SELECT ${c.join(",")} FROM ${req.params.t}`)).rows)}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/data/:t/upsert",auth,async(req,res)=>{let t=req.params.t,c=cfg[t];if(!c)return res.status(404).json({error:"Tabela inválida"});let rows=Array.isArray(req.body)?req.body:[req.body],cl=await pool.connect();try{await cl.query("BEGIN");for(let r of rows){let cols=c.filter(k=>r[k]!==undefined),v=cols.map(k=>r[k]),m=cols.map((_,i)=>`$${i+1}`),u=cols.filter(k=>k!="id").map(k=>`${k}=EXCLUDED.${k}`);await cl.query(`INSERT INTO ${t}(${cols}) VALUES(${m}) ON CONFLICT(id) DO UPDATE SET ${u},updated_at=NOW()`,v)}await cl.query("COMMIT");res.json({ok:true,count:rows.length})}catch(e){await cl.query("ROLLBACK");res.status(400).json({error:e.message})}finally{cl.release()}});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"index.html")));
init().then(()=>app.listen(PORT,"0.0.0.0",()=>console.log("Vale da Serra online",PORT))).catch(e=>{console.error(e);process.exit(1)});
