(function(){
'use strict';const B=window.V157MobileBridge;if(!B)return;
const E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>Number(x||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const norm=x=>String(x||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const admin=()=>['admin','administrador'].includes(norm(B.getUser()?.role).trim());
const allowed=p=>admin()||(B.getUser()?.permissions||[]).includes(p);
const phone=x=>{let n=String(x||'').replace(/\D/g,'');if(n.length===10||n.length===11)n='55'+n;return /^55\d{10,11}$/.test(n)?n:''};
const style=document.createElement('style');style.textContent='.v161-screen{padding:16px 12px 100px;max-width:850px;margin:auto}.v161-screen input,.v161-screen select,.v161-screen textarea{box-sizing:border-box;width:100%;min-height:46px;padding:12px;border:1px solid #ccdaec;border-radius:12px;margin:5px 0 12px;font:inherit}.v161-screen button,.v161-screen a.v161-action{display:inline-block;border:0;border-radius:12px;padding:12px;background:#0757bd;color:white;font-weight:700;margin:4px;text-decoration:none}.v161-card{background:white;border:1px solid #dce6f3;border-radius:18px;padding:16px;margin:12px 0;overflow-wrap:anywhere}.v161-card pre{white-space:pre-wrap;font:inherit;line-height:1.6}.v161-card small{display:block;color:#536477}';document.head.appendChild(style);
let screen;function open(title){if(!screen){screen=document.createElement('section');screen.className='screen v161-screen';document.getElementById('app').appendChild(screen)}document.querySelectorAll('.screen').forEach(e=>e.classList.remove('active'));document.getElementById('homeScreen').style.display='none';screen.classList.add('active');screen.innerHTML='<button id="v161Back">← Início</button><h2>'+E(title)+'</h2><div id="v161Body"></div>';screen.querySelector('#v161Back').onclick=()=>B.showHome();window.scrollTo(0,0);return screen.querySelector('#v161Body')}
function deny(){B.toast('Sem permissão para esta função.',true)}
window.v161CloseCash=function(session){if(!allowed('loja'))return deny();const box=open('Fechar caixa');box.innerHTML='<div class="v161-card"><p>Esperado em dinheiro: <b>'+money(session.expected_cash)+'</b></p><form><label>Dinheiro contado no caixa<input name="counted" type="number" inputmode="decimal" step="0.01" min="0" required></label><label>Observação<textarea name="note"></textarea></label><p id="difference"></p><button type="submit">Confirmar fechamento</button><p role="status" id="result"></p></form></div>';const form=box.querySelector('form'),input=form.elements.counted;input.oninput=()=>{box.querySelector('#difference').textContent=input.value===''?'':'Diferença: '+money(Number(input.value)-Number(session.expected_cash||0))};form.onsubmit=async e=>{e.preventDefault();if(!allowed('loja'))return deny();const n=Number(input.value);if(input.value.trim()===''||!Number.isFinite(n)||n<0)return;const button=form.querySelector('[type=submit]');if(button.disabled)return;button.disabled=true;try{const j=await B.api('/api/store/cash/close',{method:'POST',body:JSON.stringify({counted_amount:n,note:form.elements.note.value})});box.innerHTML='<div class="v161-card"><h3>Caixa fechado</h3><p>Contado: '+money(j.counted_amount)+'</p><p>Esperado: '+money(j.expected_cash)+'</p><p>Diferença: '+money(j.difference)+'</p></div>';await B.loadCash()}catch(err){box.querySelector('#result').textContent=err.message;button.disabled=false}}};
function receipt(pg,p){return ['VALE DA SERRA — COMPROVANTE DE PAGAMENTO','Produtor: '+(p?.nome||pg.prodId||'Não identificado'),'Localidade: '+(pg.localidadePrincipalPagamento||pg.localidade||p?.local||'—'),'Referência: '+(pg.mes||'—')+' • '+(pg.quinzena||'—')+'ª quinzena','Pago em: '+(pg.dataPagamento||'—'),'Corte: '+(pg.corteData||'—')+' '+(pg.corteTurno||''),'Leite: '+Number(pg.litros||0).toLocaleString('pt-BR')+' L','Bruto: '+money(pg.valorBruto),'Débitos descontados: '+money(pg.totalDebitos),'Valor pago: '+money(pg.valorPago),'Saldo devedor: '+money(pg.saldoDebitosApos),'Registro: '+(pg.id||pg.chave||'—')].join('\n')}
function whats(number,text,label){const a=document.createElement('a');a.className='v161-action';a.textContent=label;a.href='https://wa.me/'+number+'?text='+encodeURIComponent(text);a.target='_blank';a.rel='noopener noreferrer';return a}
function printReceipt(text){const w=window.open('','_blank');if(!w)return B.toast('Não foi possível abrir a impressão.',true);w.document.write('<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>Comprovante Vale da Serra</title><style>@page{margin:4mm}body{font:13px Arial;max-width:72mm;margin:auto}pre{white-space:pre-wrap;font:inherit;line-height:1.6}button{margin:12px}@media print{button{display:none}}</style><pre>'+E(text)+'</pre><button onclick="window.print()">Imprimir / Salvar PDF</button></html>');w.document.close()}
async function shareReceipt(text){
 const c=document.createElement('canvas');c.width=900;const ctx=c.getContext('2d');ctx.font='26px Arial';const lines=[];for(const line of text.split('\n')){let current='';for(const word of line.split(' ')){const next=current?current+' '+word:word;if(ctx.measureText(next).width>800&&current){lines.push(current);current=word}else current=next}lines.push(current)}c.height=120+lines.length*46;ctx.fillStyle='#ffffff';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#073466';ctx.font='26px Arial';lines.forEach((line,i)=>ctx.fillText(line,50,65+i*46));
 const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!blob)throw Error('Não foi possível gerar o comprovante.');const file=new File([blob],'comprovante-vale-da-serra.png',{type:'image/png'});
 if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({files:[file],title:'Comprovante Vale da Serra'});return}
 const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);B.toast('Imagem salva. Anexe ao WhatsApp do produtor.');
}
async function receipts(){if(!allowed('pagamentos'))return deny();const box=open('Comprovantes');box.textContent='Carregando pagamentos...';try{const j=await B.api('/api/state');if(!j.data)throw Error('Não foi possível consultar os pagamentos.');if(!allowed('pagamentos'))return deny();const s=j.data;box.innerHTML='<label>Buscar produtor ou localidade<input id="search" type="search" placeholder="Nome do produtor ou localidade"></label><label>Mês da quinzena<input id="month" type="month"></label><label>Quinzena<select id="fortnight"><option value="">Todas</option><option value="1">1ª quinzena</option><option value="2">2ª quinzena</option></select></label><div id="list"></div>';
const render=()=>{const q=norm(box.querySelector('#search').value),m=box.querySelector('#month').value,f=box.querySelector('#fortnight').value,list=box.querySelector('#list');list.replaceChildren();const rows=(s.pagamentos||[]).filter(pg=>(!m||pg.mes===m)&&(!f||String(pg.quinzena)===f)).sort((a,b)=>String(b.dataPagamento||'').localeCompare(String(a.dataPagamento||'')));for(const pg of rows){const p=(s.produtores||[]).find(p=>String(p.id)===String(pg.prodId));if(q&&!norm((p?.nome||pg.prodId)+' '+(pg.localidadePrincipalPagamento||pg.localidade||p?.local)).includes(q))continue;const card=document.createElement('article');card.className='v161-card';card.innerHTML='<h3>'+E(p?.nome||pg.prodId||'Produtor')+'</h3><small>'+E(pg.mes)+' • '+E(pg.quinzena)+'ª quinzena • '+E(pg.dataPagamento)+'</small>';if(pg.valorPago==null||pg.valorBruto==null||pg.totalDebitos==null){card.insertAdjacentHTML('beforeend','<p>Registro antigo sem valores completos. Confira o pagamento no computador.</p>');list.appendChild(card);continue}const text=receipt(pg,p),details=document.createElement('details');details.innerHTML='<summary>Ver comprovante — '+money(pg.valorPago)+'</summary><pre>'+E(text)+'</pre>';card.appendChild(details);const n=phone(p?.whatsapp);if(n)card.appendChild(whats(n,text,'WhatsApp do produtor'));else card.insertAdjacentHTML('beforeend','<p>Cadastre um WhatsApp válido no produtor para enviar.</p>');const print=document.createElement('button');print.textContent='Imprimir / PDF';print.onclick=()=>printReceipt(text);card.appendChild(print);const share=document.createElement('button');share.textContent='Compartilhar imagem';share.onclick=async()=>{share.disabled=true;try{await shareReceipt(text)}catch(e){if(e.name!=='AbortError')B.toast(e.message,true)}finally{share.disabled=false}};card.appendChild(share);list.appendChild(card)}if(!list.children.length)list.innerHTML='<div class="v161-card">Nenhum comprovante encontrado neste filtro.</div>'};box.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',render));render()}catch(err){box.textContent=err.message}}
async function alerts(){if(!admin())return deny();const box=open('Alertas WhatsApp');box.textContent='Carregando responsáveis...';try{const j=await B.api('/api/state');if(!j.data)throw Error('Não foi possível consultar os responsáveis.');box.innerHTML='<label>Buscar tanqueiro<input type="search"></label><div id="list"></div>';const groups=new Map();for(const p of j.data.produtores||[]){if(!p.tanqueiro&&!p.whatsTanqueiro)continue;const key=norm(p.tanqueiro)+'|'+phone(p.whatsTanqueiro);if(!groups.has(key))groups.set(key,{name:p.tanqueiro||'Responsável',phone:phone(p.whatsTanqueiro)});}const render=()=>{const list=box.querySelector('#list');list.replaceChildren();for(const r of groups.values()){if(!norm(r.name).includes(norm(box.querySelector('input').value)))continue;const card=document.createElement('div');card.className='v161-card';card.innerHTML='<h3>'+E(r.name)+'</h3>';if(r.phone)card.appendChild(whats(r.phone,'Olá, '+r.name+'! Por favor, não esqueça de sincronizar seu aplicativo para manter as entradas de leite atualizadas. Obrigado! Vale da Serra Laticínios','Lembrar de sincronizar'));else card.insertAdjacentHTML('beforeend','<p>WhatsApp não cadastrado ou inválido.</p>');list.appendChild(card)}if(!list.children.length)list.textContent='Nenhum responsável encontrado.'};box.querySelector('input').oninput=render;render()}catch(err){box.textContent=err.message}}
window.V164Mobile={openReceipts:receipts,openAlerts:alerts,refreshPermissions:permissions};
const grid=document.querySelector('.home-grid');if(grid){for(const [title,icon,permission,run] of [['Comprovantes','🧾','pagamentos',receipts],['Alertas WhatsApp','💬','admin',alerts],['Fechar caixa','💵','loja',async()=>{if(!allowed('loja'))return deny();try{const j=await B.api('/api/store/cash/status');if(!j.session)return B.toast('Nenhum caixa aberto. Abra o caixa no PDV.');window.v161CloseCash(j.session)}catch(e){B.toast(e.message,true)}}]]){const tile=document.createElement('button');tile.className='home-tile';tile.dataset.v161Permission=permission;tile.innerHTML='<span class="tile-ico">'+icon+'</span><span class="tile-title">'+title+'</span><small>'+({pagamentos:'Consultar e compartilhar',admin:'Lembrar de sincronizar',loja:'Conferir e encerrar'}[permission])+'</small>';tile.onclick=run;if(permission==='loja')grid.appendChild(tile);else grid.insertBefore(tile,grid.querySelector('[data-go="estoque"]'))}}
function permissions(){document.querySelectorAll('[data-v161-permission]').forEach(e=>{const visible=e.dataset.v161Permission==='admin'?admin():allowed(e.dataset.v161Permission);e.hidden=!visible;e.style.setProperty('display',visible?'flex':'none','important')})}
permissions();window.addEventListener('vds:user-changed',permissions);
})();
